name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: justt277
          outputs: |
            ./output/github-snake.svg
            ./output/github-snake-dark.svg
          snake_color: '#FFFFFF'            # White snake
          animation_duration: 12s           # Slower animation (default is 4s)


      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Generate Snake animation"
          committer: Just277 <just277@users.noreply.github.com>
          author: Just277 <just277@users.noreply.github.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
